#!/bin/bash
#PBS -N star_for-rsem_gencode_mmu
#PBS -V
#PBS -l nodes=1:ppn=8,vmem=60g,gres=localhd:50,walltime=24:00:00
set -e

# Align sequences to genome and transcriptome using STAR
# for downstream analysis with RSEM

if [ "$#" -ne 1 ]; then
	echo "usage: script <infile>"
	exit
fi

scriptpath=$(dirname "$(readlink -f "$0")")
rootpath=$scriptpath/..

infpath=$1
infname=${infpath##*/}
outfstem=${infname%%.*}

$scriptpath/star_for-rsem_gencode.sh $infpath homo_sapiens 23 8

